

name: Java CI with Maven

on:
  workflow_dispatch:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Test on (Browser ${{ matrix.browser }}, Mobile View ${{ matrix.mobileMode }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chrome]
        mobileMode: [true, false]
        headlessMode: [true]

    env:
      mobileViewRes: '500x900'
      desktopViewRes: '1920x1080'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Download .env from Gist
        run: curl -o .env "${{ secrets.GIST_ENV_URL }}"

      - name: Export .env variables
        run: |
          while IFS='=' read -r key value; do
            [[ "$key" =~ ^#.*$ || -z "$key" ]] && continue
            value="${value%\"}"
            value="${value#\"}"
            echo "$key=$value" >> $GITHUB_ENV
          done < .env

      - name: Install tools
        if: ${{ always() && matrix.headlessMode == false }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb ffmpeg

      - name: Set unique DISPLAY_NUM
        run: |
          # Generate a pseudo-random number based on workflow run ID and job name
          DISPLAY_NUM=$((100 + $(echo "${{ github.run_id }}${{ github.job }}" | cksum | cut -f1 -d' ') % 200))
          echo "DISPLAY_NUM=$DISPLAY_NUM" >> $GITHUB_ENV
          echo "Generated DISPLAY_NUM: $DISPLAY_NUM"

      - name: Start virtual display
        if: ${{ always() && matrix.headlessMode == false }}
        run: |
          if [ "${{ matrix.mobileMode }}" = "true" ]; then
            RESOLUTION=${mobileViewRes}x24
          else
            RESOLUTION=${desktopViewRes}x24
          fi
          
          Xvfb :${DISPLAY_NUM} -screen 0 $RESOLUTION &
          echo "DISPLAY=:${DISPLAY_NUM}" >> $GITHUB_ENV

      - name: Start video recording
        if: ${{ always() && matrix.headlessMode == false }}
        run: |
          if [ "${{ matrix.mobileMode }}" = "true" ]; then
            RESOLUTION=${mobileViewRes}
          else
            RESOLUTION=${desktopViewRes}
          fi
          
          ffmpeg -video_size $RESOLUTION \
          -framerate 25 \
          -f x11grab \
          -i :${DISPLAY_NUM} \
          test_recording.mp4 &
          echo $! > ffmpeg.pid

      - name: Run TestNG Tests
        run: |
          mvn test -DsuiteXmlFile=suites/all_chat_project/MainTestSuite.xml \
          -Dbrowser='${{ matrix.browser }}' -DmobileMode='${{ matrix.mobileMode }}' -DheadlessMode='${{ matrix.headlessMode }}'
        working-directory: /home/runner/work/All-Chat-UI-Test-Automation/All-Chat-UI-Test-Automation
        id: run-tests

      - name: Stop recording
        if: ${{ always() && matrix.headlessMode == false }}
        run: |
          kill $(cat ffmpeg.pid)

      - name: Upload recording
        if: ${{ always() && matrix.headlessMode == false }}
        uses: actions/upload-artifact@v6
        with:
          name: Test Recording Video (Browser ${{ matrix.browser }}, Mobile View ${{ matrix.mobileMode }})
          path: test_recording.mp4

      - name: Upload Screenshots of the Failed Tests
        if: ${{ failure() }}
        uses: actions/upload-artifact@v6
        with:
          name: Screenshots of failed tests (Browser ${{ matrix.browser }}, Mobile View ${{ matrix.mobileMode }})
          path: src/main/screenshots/**

      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: Cucumber Test Report (Browser ${{ matrix.browser }}, Mobile View ${{ matrix.mobileMode }})
          path: target/cucumber-report.html